 SELECT
    RPT_CATEGORY.SERV_PROV_CODE,
    RPT_CATEGORY.RPT_CATEGORY_ID,
    RPT_CATEGORY.CATEGORY_NAME,
    RPT_DETAIL.REPORT_NAME,
    RPT_DETAIL.REPORT_DESCRIPTION,
    RPT_DETAIL.REPORT_TYPE,
    RPT_DETAIL.REPORT_LINK,
    RPT_DETAIL.REPORT_FORMAT,
    RPT_DETAIL.DOC_GROUP,
    RPT_DETAIL.DOC_CATEGORY,
    RPT_PARAMETER.PARAMETER_NAME,
    RPT_PARAMETER.PARAMETER_TYPE,
    RPT_PARAMETER.PARAMETER_SOURCE,
    RPT_PARAMETER.PARAMETER_REQUIRED,
    RPT_PARAMETER.DEFAULT_VALUE
    FROM RPT_CATEGORY, RPT_DETAIL, RPT_PARAMETER
    WHERE     (RPT_CATEGORY.RPT_CATEGORY_ID = RPT_DETAIL.CATEGORY_ID)
    AND (RPT_PARAMETER.REPORT_ID = RPT_DETAIL.REPORT_ID)